name: AsyncAPI documents processing
on: push
permissions:
  contents: write
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    #"standard step" where repo needs to be checked-out first
    - name: Checkout repo
      uses: actions/checkout@v2
      
    #In case you do not want to use defaults, you for example want to use different template
    - name: Generating HTML from my AsyncAPI document with custom template
      uses: asyncapi/github-action-for-cli@v3.0.1  #always use latest tag as each is pushed to docker
      with:
        template: '@asyncapi/html-template@0.15.4'  #In case of template from npm, because of @ it must be in quotes
        filepath: docs/api/my-asyncapi.yml
        parameters: --force-write -p baseHref=/test-experiment/ sidebarOrganization=byTags #space separated list of key/values
        output: generated-html
      continue-on-error: true

    - name: Generating HTML from my AsyncAPI document with custom template
      uses: Shurtu-gal/github-action-for-cli@4983c73c8433b45e99d8e9f622cd1ed8a9e0b5a8 #always use latest tag as each is pushed to docker
      with:
        template: '@asyncapi/html-template@0.15.4'  #In case of template from npm, because of @ it must be in quotes
        filepath: docs/api/my-asyncapi.yml
        parameters: --force-write -p baseHref=/test-experiment/ sidebarOrganization=byTags #space separated list of key/values
        output: generated-html
      continue-on-error: true
        
    #Using another action that takes generated HTML and pushes it to GH Pages
    - name: Deploy GH page
      uses: JamesIves/github-pages-deploy-action@4.0.0
      with:
        folder: generated-html
        branch: gh-pages
        token: ${{ secrets.GITHUB_TOKEN }}
