name: GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  generate:
    runs-on: ["ubuntu-latest"]
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: generate
        uses: asyncapi/github-action-for-cli@v3.1.2
        with:
          cli_version: v2.12.1
          template: "@asyncapi/html-template@3.1.0"
          filepath: docs/api/my-asyncapi.yml
          parameters: --use-new-generator
          output: out

      - name: deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out
